// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// templates/navbar.templ

package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"sticky top-0 z-50 border-b border-gray-800 bg-gray-950/80 backdrop-blur-md\"><div class=\"mx-auto flex max-w-6xl items-center justify-between px-6 py-4\"><a href=\"/\" class=\"text-xl font-bold text-white hover:text-purple-400 transition\">Zack</a><div class=\"flex gap-8 text-sm font-medium\"><a href=\"/\" class=\"hover:text-purple-400 transition\" hx-get=\"/\" hx-target=\"#content\" hx-push-url=\"true\" hx-swap=\"innerHTML\">About</a> <a href=\"/projects\" class=\"hover:text-purple-400 transition\" hx-get=\"/projects\" hx-target=\"#content\" hx-push-url=\"true\" hx-swap=\"innerHTML\">Projects</a> <a href=\"/blog\" class=\"hover:text-purple-400 transition\" hx-get=\"/blog\" hx-target=\"#content\" hx-push-url=\"true\" hx-swap=\"innerHTML\">Blog</a></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
